mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.bmp
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.gif
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.jpg
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.jpeg
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.pjpeg
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.png
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.tif
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.tiff
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.BMP
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.GIF
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.JPG
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.JPEG
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.PJPEG
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.PNG
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.TIF
mogrify -adaptive-resize 800x -format jpg -quality 100 -path converted_images raw_files/*.TIFF